---
BasedOnStyle: LLVM
AlignEscapedNewlines: Left
AlignOperands: AlignAfterOperator
AllowAllArgumentsOnNextLine: false
AllowAllConstructorInitializersOnNextLine: false
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortEnumsOnASingleLine: false
AllowShortFunctionsOnASingleLine: None
AllowShortLambdasOnASingleLine: None
AlwaysBreakTemplateDeclarations: Yes
BreakBeforeBraces: Custom
BreakInheritanceList: BeforeComma
BreakConstructorInitializers: BeforeComma
BraceWrapping:
  AfterEnum: true
  AfterClass: true
  AfterUnion: true
  AfterStruct: true
  AfterFunction: true
  AfterCaseLabel: true
  AfterNamespace: true
  AfterControlStatement: true
  BeforeElse: true
  BeforeCatch: true
  SplitEmptyRecord: false
  SplitEmptyFunction: false
  SplitEmptyNamespace: false
ColumnLimit: 0
ConstructorInitializerIndentWidth: 2
ContinuationIndentWidth: 2
KeepEmptyLinesAtTheStartOfBlocks: false
NamespaceIndentation: All
ObjCBlockIndentWidth: 2
ReflowComments: false
SortIncludes: false
SpaceBeforeCtorInitializerColon: false
SpaceBeforeInheritanceColon: false
SpacesInContainerLiterals: false
TabWidth: 2
...
